"""Runtime constants shared across worker and runtime modules."""

# TaskQ defaults
DEFAULT_TASKQ_MAX_PARALLEL = 3
DEFAULT_TASKQ_POLL_INTERVAL_SECONDS = 5

# Git/runtime defaults
DEFAULT_BASE_BRANCH = "main"
DEFAULT_REPOS_ROOT = "~/documents/repos"
DEFAULT_WORKTREES_ROOT = f"{DEFAULT_REPOS_ROOT}/worktrees"
DEFAULT_GIT_SHORT_TIMEOUT_SECONDS = 10
DEFAULT_GIT_LONG_TIMEOUT_SECONDS = 30

# Docker image and container defaults
DEFAULT_DOCKER_IMAGE = "sisifo/opencode:latest"
DEFAULT_OPENCODE_SERVER_HOST = "0.0.0.0"
DEFAULT_OPENCODE_SERVER_PORT = 8000
DEFAULT_OPENCODE_HOST = "127.0.0.1"
DEFAULT_OPENCODE_SERVER_CMD = [
    "serve",
    "--hostname",
    DEFAULT_OPENCODE_SERVER_HOST,
    "--port",
    str(DEFAULT_OPENCODE_SERVER_PORT),
]

# OpenCode container directory paths
DEFAULT_CONTAINER_OPENCODE_CONFIG_DIR = "/root/.config/opencode"
DEFAULT_CONTAINER_OPENCODE_DATA_DIR = "/root/.local/share/opencode"

# OpenCode execution defaults
DEFAULT_PLAN_AGENT = "plan"
DEFAULT_BUILD_AGENT = "build"
DEFAULT_PLAN_MODEL = "openai/gpt-5.3-codex"
DEFAULT_BUILD_MODEL = "openai/gpt-5.3-codex"
DEFAULT_PLAN_VARIANT = "xhigh"
DEFAULT_BUILD_VARIANT = "xhigh"
DEFAULT_PLAN_TIMEOUT_SECONDS = 300
DEFAULT_BUILD_TIMEOUT_SECONDS = 600
DEFAULT_OPENCODE_MAKE_PLAN_COMMAND = "make-plan-sisifo"
DEFAULT_OPENCODE_EXECUTE_PLAN_COMMAND = "execute-plan-sisifo"

# Review defaults
DEFAULT_REVIEW_TIMEOUT_SECONDS = 3600

# Docker runtime defaults
DEFAULT_PORT_RANGE_START = 30000
DEFAULT_PORT_RANGE_END = 65535
DEFAULT_DOCKER_INSPECT_TIMEOUT_SECONDS = 5
DEFAULT_DOCKER_RUN_TIMEOUT_SECONDS = 30
DEFAULT_DOCKER_STOP_TIMEOUT_SECONDS = 10
DEFAULT_DOCKER_STOP_BUFFER_SECONDS = 5
DEFAULT_DOCKER_REMOVE_TIMEOUT_SECONDS = 10
DEFAULT_DOCKER_LOGS_TIMEOUT_SECONDS = 5
DEFAULT_DOCKER_PS_TIMEOUT_SECONDS = 5
DEFAULT_DOCKER_EXEC_TIMEOUT_SECONDS = 5
DEFAULT_DOCKER_CONTAINER_READY_TIMEOUT_SECONDS = 30
DEFAULT_DOCKER_CONTAINER_READY_INTERVAL_SECONDS = 0.5
DEFAULT_DOCKER_CONTAINER_STABILIZE_SECONDS = 0.5
